global:
  scrape_interval: 5s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9080
  - job_name: demo
    static_configs:
      - targets:
        - demo.promlabs.com:10000
        - demo.promlabs.com:10001
        - demo.promlabs.com:10002